#!/bin/bash

clear

display_mode=2

for mapId in {0..4}; do
	echo "Arena: $mapId"
    for initPos in True False; do
        python3 tetracomposibot.py config_fin "$mapId" "$initPos" "$display_mode"
    done
done
